services:
  superlink:
    image: flwr/superlink:1.22.0
    ports:
      - "9093:9093"
    volumes:
      - ./certificates:/app/certificates
    command: >
      --insecure
      --isolation process

  supernode-1:
    image: ykdz/ra-tls-supernode:latest
    ports:
      - "9094:9094"
    volumes:
      - ./certificates/ca.crt:/app/certificates/ca.crt
    command: >
      --insecure
      --superlink superlink:9092
      --node-config "partition-id=0 num-partitions=2"
      --clientappio-api-address 0.0.0.0:9094
      --isolation process
    environment:
      - SUPERLINK_HOST=superlink
      - SUPERLINK_PORT=9092
